SAMPLE_COURSES = [
    {
        "title": "Python cho nguoi moi bat dau",
        "category": "Programming",
        "level": "Beginner",
        "description": "Khoa hoc Python co ban cho nguoi moi hoc lap trinh va ren luyen tu duy logic.",
        "skills": ["python", "logic", "variables", "loops"],
    },
    {
        "title": "Java co ban",
        "category": "Programming",
        "level": "Beginner",
        "description": "Nhap mon Java voi bien, cau lenh dieu kien, vong lap va huong doi tuong co ban.",
        "skills": ["java", "oop", "logic", "loops"],
    },
    {
        "title": "C++ can ban cho sinh vien ky thuat",
        "category": "Programming",
        "level": "Beginner",
        "description": "Hoc C++ co ban de lam quen voi lap trinh cau truc, ham va mang.",
        "skills": ["c++", "functions", "arrays", "logic"],
    },
    {
        "title": "Lap trinh huong doi tuong voi Java",
        "category": "Programming",
        "level": "Intermediate",
        "description": "Khoa hoc tap trung vao class, object, inheritance, polymorphism va ung dung OOP bang Java.",
        "skills": ["java", "oop", "inheritance", "polymorphism"],
    },
    {
        "title": "Cau truc du lieu va giai thuat bang Python",
        "category": "Programming",
        "level": "Intermediate",
        "description": "Ren luyen tu duy giai thuat voi list, stack, queue, tree va cac bai toan tim kiem sap xep.",
        "skills": ["python", "algorithms", "data structures", "problem solving"],
    },
    {
        "title": "Web Development voi HTML CSS JavaScript",
        "category": "Web Development",
        "level": "Beginner",
        "description": "Xay dung trang web co ban voi HTML, CSS va JavaScript cho nguoi moi bat dau.",
        "skills": ["html", "css", "javascript", "responsive"],
    },
    {
        "title": "ReactJS cho nguoi moi bat dau",
        "category": "Web Development",
        "level": "Beginner",
        "description": "Hoc ReactJS co ban, component, props, state va cach tao giao dien mot trang.",
        "skills": ["react", "javascript", "components", "state"],
    },
    {
        "title": "Xay dung REST API voi FastAPI",
        "category": "Web Development",
        "level": "Intermediate",
        "description": "Tao REST API bang FastAPI, xu ly request response, validation va ket noi database.",
        "skills": ["fastapi", "python", "api", "backend"],
    },
    {
        "title": "Node.js va Express can ban",
        "category": "Web Development",
        "level": "Intermediate",
        "description": "Phat trien backend web voi Node.js, Express va ket noi REST API.",
        "skills": ["nodejs", "express", "api", "backend"],
    },
    {
        "title": "SQL cho nguoi moi bat dau",
        "category": "Database",
        "level": "Beginner",
        "description": "Hoc truy van du lieu voi SELECT, WHERE, ORDER BY va cac lenh SQL co ban.",
        "skills": ["sql", "mysql", "select", "database"],
    },
    {
        "title": "Thiet ke co so du lieu quan he",
        "category": "Database",
        "level": "Intermediate",
        "description": "Hoc phan tich thuc the lien ket, chuan hoa du lieu va thiet ke bang trong co so du lieu.",
        "skills": ["database design", "erd", "normalization", "sql"],
    },
    {
        "title": "MongoDB cho ung dung web",
        "category": "Database",
        "level": "Intermediate",
        "description": "Lam quen voi MongoDB, collection, document, CRUD va cach su dung trong web app.",
        "skills": ["mongodb", "nosql", "crud", "database"],
    },
    {
        "title": "Data Analysis voi Python",
        "category": "Data Science",
        "level": "Beginner",
        "description": "Phan tich du lieu co ban bang Python, NumPy, Pandas va truc quan hoa du lieu.",
        "skills": ["python", "pandas", "numpy", "data analysis"],
    },
    {
        "title": "Data Visualization voi Power BI",
        "category": "Data Science",
        "level": "Beginner",
        "description": "Tao dashboard va bao cao truc quan voi Power BI cho nguoi moi hoc phan tich du lieu.",
        "skills": ["power bi", "dashboard", "visualization", "reporting"],
    },
    {
        "title": "Machine Learning can ban",
        "category": "Data Science",
        "level": "Intermediate",
        "description": "Nhap mon machine learning voi supervised learning, classification va model evaluation.",
        "skills": ["machine learning", "python", "scikit-learn", "classification"],
    },
    {
        "title": "Deep Learning voi TensorFlow",
        "category": "Artificial Intelligence",
        "level": "Advanced",
        "description": "Xay dung mang neural network voi TensorFlow va Keras cho cac bai toan hoc sau.",
        "skills": ["deep learning", "tensorflow", "keras", "neural networks"],
    },
    {
        "title": "Xu ly ngon ngu tu nhien co ban",
        "category": "Artificial Intelligence",
        "level": "Intermediate",
        "description": "Hoc NLP co ban, tach tu, vector hoa van ban va ung dung trong phan loai van ban.",
        "skills": ["nlp", "text processing", "tf-idf", "python"],
    },
    {
        "title": "UI UX Design Fundamentals",
        "category": "Design",
        "level": "Beginner",
        "description": "Tim hieu nguyen ly UI UX, wireframe, prototype va trai nghiem nguoi dung co ban.",
        "skills": ["ui", "ux", "wireframe", "prototype"],
    },
]
